version: '3'
services:
  db:
    image: mysql
    volumes:
      - data:/var/lib/mysql
      - ./mysql.cnf:/etc/mysql/conf.d/mysql.cnf
    environment:
      MYSQL_ROOT_PASSWORD: pass
  web:
    image: nginx
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    depends_on:
      - app
  app:
    build: .
    volumes:
      - .:/myapp
      - bundle:/usr/local/bundle
    environment:
      DOCKER_COMPOSE: 1
    ports:
      - "3000:3000"
    depends_on:
      - db
    tty: true
    # command: bundle exec rails s -p 3000 -b '0.0.0.0'
    # command: ["puma"]
volumes:
  data:
  bundle:
